server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://<ip>:<port>/<databaseName>
    username: username
    password: password
    hikari:
      auto-commit: false
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false